services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.12
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9069"
    volumes:
      - ./data:/var/lib/clickhouse/user_files/data:rw
      - ./configs/default_user.xml:/etc/clickhouse-server/users.d/default_user.xml
      - ./configs/config.xml:/etc/clickhouse-server/config.d/config.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144